### ISSUE TITLE
ImportError: cannot import name 'get_default_audio_adapter'

### ISSUE THREAD

**Issue by filesnx** [olaviinha/NeuralAudioStemSeparation#1]
I'm using the colab, and this error started showing from today in the Separate section.

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-8-4e6c80539f1a> in <module>()
>      30 
>      31 from spleeter.separator import Separator
> ---> 32 from spleeter.audio.adapter import get_default_audio_adapter
>      33 separator = Separator('/content/cfg.json')
>      34 if input_type == "dir" or input_type == "youtube":
> 
> ImportError: cannot import name 'get_default_audio_adapter'
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.
> ---------------------------------------------------------------------------

**Comment by olaviinha** [comment]
Issue is now fixed. Thanks for reporting!
