### ISSUE TITLE
Running the "separate" step after finished setup (green) fails

### ISSUE THREAD

**Issue by keljaus** [olaviinha/NeuralAudioStemSeparation#2]
Tried to use the program with URL: youtube.com/watch?v=vAClAa1MaqM + .wav file in google drive (single file) and got error in after separation-step.

Steps for reproduce:

1. I setup my google drive in this program's collab area with "green" finished status
2. I added input URL / direct path Google Drive path to my wav file
3. I ran the "separate" step

Result: 
youtube url:
mkdir: cannot create directory ‘temp/spleets’: No such file or directory
mkdir: cannot create directory ‘youtube.com/watch?v=vAClAa1MaqM’: No such file or directory
We're not sure what you want to separate. Please check the input field.

.wav file:
mkdir: cannot create directory ‘temp/spleets’: No such file or directory
We're not sure what you want to separate. Please check the input field.

Expected:
the program would create me the 4 output files to the output location (google drive)

NOTE: This program was still doing it's job correctly ~1 month ago, so there has to be something that got broken during last month

**Comment by olaviinha** [comment]
[Fixed](https://github.com/olaviinha/NeuralAudioStemSeparation/commit/a7dfc2e45e581b93704ca8723ad06aff0bba4258)

I think issue was caused by update in [inhagcutils](https://github.com/olaviinha/inhagcutils).

**Comment by olaviinha** [comment]
Btw, this may also occur if you have dropped an audio file to Drive and the sync has not been completed yet.
